version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/tomcat9/webapps
permissions:
  - object: /opt/tomcat/tomcat9/webapps
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
